# Held-out model evaluation and transportability

This notebook generates absolute-risk
predictions for every untouched assessment row from registry-verified trained-model bundles, and
reports delayed-entry-aware discrimination, calibration, and prediction error at 365 and 730 days
with patient-level bootstrap uncertainty. It computes the pooled-versus-held-out transportability gap
and the centre-specific complexity-value table. It generates no explanation, attribution,
prediction-stability, recalibration, or sensitivity result

In [1]:
from pathlib import Path

import pandas as pd
from IPython.display import display

from crc_folfox.evaluate.workflow import run_evaluation_workflow

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent
ANALYSIS_DIRECTORY = PROJECT_ROOT / "analysis" / "out" / "current"

result = run_evaluation_workflow(ANALYSIS_DIRECTORY)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/src/crc_folfox/evaluate/pooling.py:161: RuntimeWarning: Mean of empty slice
  conditional_mean = np.nanmean(np.stack(per_repeat_conditional), axis=0)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)
/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/generalized_linear_model.py:1342: PerfectSeparationWarning: Perfect separation or prediction detected, parameter may not be identified
  warnings.warn(msg, category=PerfectSeparationWarning)

/Users/camilasarmiento/Documents/Data Freelancer/portfolio/CRC/.venv/lib/python3.12/site-packages/statsmodels/genmod/families/links.py:989: RuntimeWarning: overflow encountered in exp
  return 1 - np.exp(-np.exp(z))

In [2]:
import json

assert result.artifacts is not None
manifest = json.loads(result.artifacts.evaluation_manifest.read_text(encoding="utf-8"))
keys = ("input_hashes", "software_versions", "row_counts")
display({"workflow": "held-out model evaluation", **{key: manifest[key] for key in keys}})

{'workflow': 'held-out model evaluation',
 'input_hashes': {'analysis_dataset.csv': '6b9e28099f547150324b33be900d228d22b411b7dbe0d68e1e08551aaab6740e',
  'data_dictionary.json': '74afd2302e93585bda59f4ecb01b536da05c0a44da14f07f66e8b660eeb27496',
  'feature_manifest.json': 'cc891bcdca2b06179dd33e4bc55160e0e048557059e57b0b02789c7b18dc0f73',
  'fit_summary.csv': 'dfb77a84220741ad94e1362a90eaaa8c2240980ddd7c59ef0ed039548d60ad9b',
  'model_registry.json': '2695e55ae3ed97a9e98d5ff419544dafb7ee21e9bb65c6e6ca4ae6bd3770596f',
  'run_manifest.json': 'd11982f0e9cd7f740cae7432744fa23aba336d944f7236a2f10429e775b84bfd',
  'training_report.md': '393ef27916c7182a27d5a04f38c8684f62acc6e8b75776321fdbcdf055ac9875',
  'tuning_summary.csv': 'cdc1a195c921f30c54c81059276e5262041c75697265a608d8781720d2c42115'},
 'software_versions': {'lifelines': '0.30.3',
  'numpy': '2.5.1',
  'pandas': '2.3.3',
  'statsmodels': '0.14.6'},
 'row_counts': {'calibration_curves.csv': 640,
  'complexity_value_summary.csv': 252,
  'entry_support_summary.csv': 24,
  'performance_summary.csv': 672,
  'transportability_summary.csv': 240}}

## Evaluation populations, designs, and entry support

Two designs are evaluated for the **same** eligible patients of each centre: `iecv` (the single
institution-held-out model, which never saw that centre) and `pooled` (that patient's pooled
out-of-fold prediction, averaged across admissible repeats). The pooled comparator is a mixed-centre
comparator by design and is never used as a substitute for institution holdout.

In [3]:
display(result.entry_support_summary)

,endpoint,group,day,n_eligible,n_events,n_event_free,n_censored_before
0,OS,DFCI,84.0,86,1,83,2
1,OS,DFCI,365.0,150,16,128,6
2,OS,DFCI,730.0,184,51,119,14
3,OS,MSK,84.0,136,3,133,0
4,OS,MSK,365.0,214,26,183,5
5,OS,MSK,730.0,269,77,178,14
6,OS,VICC,84.0,15,0,14,1
7,OS,VICC,365.0,41,6,31,4
8,OS,VICC,730.0,63,21,33,9
9,OS,All,84.0,237,4,230,3
10,OS,All,365.0,405,48,342,15
11,OS,All,730.0,516,149,330,37
12,TTNT-D,DFCI,84.0,84,7,75,2
13,TTNT-D,DFCI,365.0,118,70,43,5
14,TTNT-D,DFCI,730.0,121,90,26,5
15,TTNT-D,MSK,84.0,133,20,113,0
16,TTNT-D,MSK,365.0,168,118,48,2
17,TTNT-D,MSK,730.0,176,138,34,4
18,TTNT-D,VICC,84.0,14,1,12,1
19,TTNT-D,VICC,365.0,27,13,11,3
20,TTNT-D,VICC,730.0,31,22,6,3
21,TTNT-D,All,84.0,231,28,200,3
22,TTNT-D,All,365.0,313,201,102,10
23,TTNT-D,All,730.0,328,250,66,12

## Scope inventory

48 evaluation scopes (2 endpoints x 2 designs x 3 centres x 4 required Cox models) each carry 14
performance rows: two horizon-independent primary rows (truncation-aware concordance, integrated
Brier score), eight horizon-specific primary rows (time-dependent AUC, Brier score, calibration
slope, calibration-in-the-large at 365 and 730 days), and four entry-conditional secondary
calibration rows. `ltrc_rrf` and `ltrc_boosting` were found `technically_ineligible` during model training and
contribute no scope.

In [4]:
inventory = (
    result.performance_summary.groupby(["endpoint", "design", "model"], sort=True)
    .agg(rows=("metric", "count"))
    .reset_index()
)
display(inventory)

   endpoint  design            model  rows
0        OS    iecv         core_cox    42
1        OS    iecv  elastic_net_cox    42
2        OS    iecv      minimal_cox    42
3        OS    iecv       spline_cox    42
4        OS  pooled         core_cox    42
5        OS  pooled  elastic_net_cox    42
6        OS  pooled      minimal_cox    42
7        OS  pooled       spline_cox    42
8    TTNT-D    iecv         core_cox    42
9    TTNT-D    iecv  elastic_net_cox    42
10   TTNT-D    iecv      minimal_cox    42
11   TTNT-D    iecv       spline_cox    42
12   TTNT-D  pooled         core_cox    42
13   TTNT-D  pooled  elastic_net_cox    42
14   TTNT-D  pooled      minimal_cox    42
15   TTNT-D  pooled       spline_cox    42

## Metric set and delayed-entry evidence

Every reported estimator explicitly accepts `entry`, `exit`, and `event` and excludes a patient from
a risk set before entry: the shared delayed-entry censoring KM
(`crc_folfox.evaluate.censoring.fit_censoring_km`/`horizon_weights`), truncation-aware concordance,
Uno-style IPCW time-dependent AUC, the model-training workflow's delayed-entry IPCW Brier core (integrated over
the locked `[365, 730]`-day grid for IBS), and a complementary-log-log-link weighted GLM for the
calibration slope and calibration-in-the-large. `lifelines.utils.concordance_index` and every
`sksurv.metrics.*` survival metric are named ineligible because their interfaces carry no entry time
(`evaluation-spec.md`, "Explicitly ineligible software").

**Decision-curve analysis is prospectively omitted**: no prespecified clinical action or threshold
range is supplied, and the 84-day risk set has only four eligible deaths overall. `net_benefit_gain`
is `not_applicable` in every complexity-value row.

In [5]:
reporting_status_counts = result.performance_summary["reporting_status"].value_counts()
display(reporting_status_counts)

reporting_status
estimable_imprecise    239
not_computable         224
estimable              209
Name: count, dtype: int64

## Discrimination, calibration, and prediction-error tables

Every cell carries a point estimate, a 95% bootstrap interval (2000 patient-level resamples per
`(endpoint, centre)`, shared across every design/model/horizon/metric of that cell so comparisons are
exactly paired), support counts, and the prespecified reporting status. A wide interval is
`estimable_imprecise`, never relabelled `not_computable`.

In [6]:
display(
    result.performance_summary[
        [
            "endpoint",
            "design",
            "centre",
            "model",
            "metric",
            "horizon",
            "risk_scale",
            "estimate",
            "ci_lower",
            "ci_upper",
            "n_eligible",
            "n_events",
            "reporting_status",
            "reason",
        ]
    ].head(30)
)

,endpoint,design,centre,model,metric,horizon,risk_scale,estimate,ci_lower,ci_upper,n_eligible,n_events,reporting_status,reason
0,OS,iecv,DFCI,minimal_cox,concordance,,unconditional,0.668727,0.613807,0.721806,227,129,estimable,
1,OS,iecv,DFCI,minimal_cox,ibs,,unconditional,0.167130,0.128916,0.207500,184,51,estimable,
2,OS,iecv,DFCI,minimal_cox,auc,365.0,unconditional,0.675138,0.550361,0.799338,150,16,estimable_imprecise,insufficient_events
3,OS,iecv,DFCI,minimal_cox,brier,365.0,unconditional,0.097455,0.058781,0.141673,150,16,estimable_imprecise,insufficient_events
4,OS,iecv,DFCI,minimal_cox,slope,365.0,unconditional,1.078809,0.413384,2.036985,150,16,estimable_imprecise,"insufficient_events,precision_target_missed"
5,OS,iecv,DFCI,minimal_cox,citl,365.0,unconditional,0.475061,-0.090806,0.894424,150,16,estimable_imprecise,"insufficient_events,precision_target_missed"
6,OS,iecv,DFCI,minimal_cox,slope,365.0,entry_conditional,1.356828,0.757481,2.306748,150,16,estimable_imprecise,"insufficient_events,precision_target_missed"
7,OS,iecv,DFCI,minimal_cox,citl,365.0,entry_conditional,0.683070,0.111430,1.116470,150,16,estimable_imprecise,"insufficient_events,precision_target_missed"
8,OS,iecv,DFCI,minimal_cox,auc,730.0,unconditional,0.682666,0.599178,0.761335,184,51,estimable,
9,OS,iecv,DFCI,minimal_cox,brier,730.0,unconditional,0.202202,0.165339,0.241387,184,51,estimable,
10,OS,iecv,DFCI,minimal_cox,slope,730.0,unconditional,0.974309,0.563704,1.467145,184,51,estimable,
11,OS,iecv,DFCI,minimal_cox,citl,730.0,unconditional,0.335969,0.032932,0.596928,184,51,estimable_imprecise,precision_target_missed
12,OS,iecv,DFCI,minimal_cox,slope,730.0,entry_conditional,0.922191,0.575371,1.372428,184,51,estimable,
13,OS,iecv,DFCI,minimal_cox,citl,730.0,entry_conditional,0.519889,0.211568,0.788719,184,51,estimable_imprecise,precision_target_missed
14,OS,pooled,DFCI,minimal_cox,concordance,,unconditional,0.664667,0.610559,0.717684,227,129,estimable,
15,OS,pooled,DFCI,minimal_cox,ibs,,unconditional,0.168202,0.130564,0.208075,184,51,estimable,
16,OS,pooled,DFCI,minimal_cox,auc,365.0,unconditional,0.646835,0.520968,0.775739,150,16,estimable_imprecise,"insufficient_events,precision_target_missed"
17,OS,pooled,DFCI,minimal_cox,brier,365.0,unconditional,0.098518,0.059422,0.142961,150,16,estimable_imprecise,insufficient_events
18,OS,pooled,DFCI,minimal_cox,slope,365.0,unconditional,0.884480,0.262812,1.754226,150,16,estimable_imprecise,"insufficient_events,precision_target_missed"
19,OS,pooled,DFCI,minimal_cox,citl,365.0,unconditional,0.455190,-0.118891,0.880571,150,16,estimable_imprecise,"insufficient_events,precision_target_missed"
20,OS,pooled,DFCI,minimal_cox,slope,365.0,entry_conditional,1.167843,0.635180,2.007623,150,16,estimable_imprecise,"insufficient_events,precision_target_missed"
21,OS,pooled,DFCI,minimal_cox,citl,365.0,entry_conditional,0.686580,0.119152,1.132341,150,16,estimable_imprecise,"insufficient_events,precision_target_missed"
22,OS,pooled,DFCI,minimal_cox,auc,730.0,unconditional,0.672697,0.587460,0.754238,184,51,estimable,
23,OS,pooled,DFCI,minimal_cox,brier,730.0,unconditional,0.204675,0.168140,0.244230,184,51,estimable,
24,OS,pooled,DFCI,minimal_cox,slope,730.0,unconditional,0.870751,0.477370,1.355645,184,51,estimable,
25,OS,pooled,DFCI,minimal_cox,citl,730.0,unconditional,0.302280,-0.009443,0.567253,184,51,estimable_imprecise,precision_target_missed
26,OS,pooled,DFCI,minimal_cox,slope,730.0,entry_conditional,0.835240,0.509759,1.254994,184,51,estimable,
27,OS,pooled,DFCI,minimal_cox,citl,730.0,entry_conditional,0.493453,0.181760,0.767848,184,51,estimable_imprecise,precision_target_missed
28,OS,iecv,DFCI,core_cox,concordance,,unconditional,NaN,NaN,NaN,0,0,not_computable,fit_failed
29,OS,iecv,DFCI,core_cox,ibs,,unconditional,NaN,NaN,NaN,0,0,not_computable,fit_failed

## Calibration figures and entry-conditional coherence

Panel figures (one per endpoint/design/horizon, a centre-by-model grid) are saved under
`figures/` from the aggregate quintile calibration curves only -- no patient-level point is plotted.
The entry-conditional secondary risk scale is reported beside the unconditional primary scale as a
prespecified coherence check.

In [7]:
figure_files = sorted(p.name for p in result.artifacts.figures.glob("*.png"))
display(figure_files)

coherence = (
    result.performance_summary[(result.performance_summary["metric"].isin(["citl", "slope"]))]
    .pivot_table(
        index=["endpoint", "design", "centre", "model", "metric", "horizon"],
        columns="risk_scale",
        values="estimate",
    )
    .reset_index()
)
display(coherence.head(20))

['calibration_OS_iecv_365.png',
 'calibration_OS_iecv_730.png',
 'calibration_OS_pooled_365.png',
 'calibration_OS_pooled_730.png',
 'calibration_TTNT-D_iecv_365.png',
 'calibration_TTNT-D_iecv_730.png',
 'calibration_TTNT-D_pooled_365.png',
 'calibration_TTNT-D_pooled_730.png']

risk_scale,endpoint,design,centre,model,metric,horizon,entry_conditional,unconditional
0,OS,iecv,DFCI,elastic_net_cox,citl,365.0,0.577075,0.382423
1,OS,iecv,DFCI,elastic_net_cox,citl,730.0,0.413563,0.230114
2,OS,iecv,DFCI,elastic_net_cox,slope,365.0,1.143457,0.949708
3,OS,iecv,DFCI,elastic_net_cox,slope,730.0,0.943922,0.994333
4,OS,iecv,DFCI,minimal_cox,citl,365.0,0.683070,0.475061
5,OS,iecv,DFCI,minimal_cox,citl,730.0,0.519889,0.335969
6,OS,iecv,DFCI,minimal_cox,slope,365.0,1.356828,1.078809
7,OS,iecv,DFCI,minimal_cox,slope,730.0,0.922191,0.974309
8,OS,iecv,DFCI,spline_cox,citl,365.0,0.549646,0.364477
9,OS,iecv,DFCI,spline_cox,citl,730.0,0.385909,0.205324
10,OS,iecv,DFCI,spline_cox,slope,365.0,0.918501,0.774690
11,OS,iecv,DFCI,spline_cox,slope,730.0,0.816887,0.834105
12,OS,iecv,MSK,minimal_cox,citl,365.0,0.599848,0.431785
13,OS,iecv,MSK,minimal_cox,citl,730.0,0.271453,0.102397
14,OS,iecv,MSK,minimal_cox,slope,365.0,0.948612,0.958650
15,OS,iecv,MSK,minimal_cox,slope,730.0,0.763567,0.787701
16,OS,iecv,MSK,spline_cox,citl,365.0,0.690282,0.507692
17,OS,iecv,MSK,spline_cox,citl,730.0,0.318253,0.143648
18,OS,iecv,MSK,spline_cox,slope,365.0,0.826062,0.782761
19,OS,iecv,MSK,spline_cox,slope,730.0,0.611722,0.574759

## Transportability gap

`gap = pooled - iecv` on the same eligible patients and the same paired bootstrap resamples, for the
ten primary metric-horizon combinations. `higher_is_better` is recorded explicitly per metric so
direction is unambiguous rather than left to the reader.

In [8]:
display(
    result.transportability_summary[
        [
            "endpoint",
            "centre",
            "model",
            "metric",
            "horizon",
            "higher_is_better",
            "gap",
            "gap_ci_lower",
            "gap_ci_upper",
            "pooled_status",
            "iecv_status",
        ]
    ]
)

,endpoint,centre,model,metric,horizon,higher_is_better,gap,gap_ci_lower,gap_ci_upper,pooled_status,iecv_status
0,OS,DFCI,minimal_cox,concordance,,True,-0.004060,-0.015304,0.006505,estimable,estimable
1,OS,DFCI,minimal_cox,ibs,,False,0.001072,-0.000610,0.002740,estimable,estimable
2,OS,DFCI,minimal_cox,auc,365.0,True,-0.028303,-0.061551,-0.001110,estimable_imprecise,estimable_imprecise
3,OS,DFCI,minimal_cox,auc,730.0,True,-0.009968,-0.025986,0.005786,estimable,estimable
4,OS,DFCI,minimal_cox,brier,365.0,False,0.001062,0.000221,0.001994,estimable_imprecise,estimable_imprecise
...,...,...,...,...,...,...,...,...,...,...,...
235,TTNT-D,VICC,spline_cox,brier,730.0,False,-0.008207,-0.023634,0.008480,estimable_imprecise,estimable_imprecise
236,TTNT-D,VICC,spline_cox,citl,365.0,,0.168297,0.083888,0.264401,estimable_imprecise,estimable_imprecise
237,TTNT-D,VICC,spline_cox,citl,730.0,,0.091103,0.037804,0.152853,estimable_imprecise,estimable_imprecise
238,TTNT-D,VICC,spline_cox,slope,365.0,,0.104520,-0.174860,0.926274,estimable_imprecise,estimable_imprecise
239,TTNT-D,VICC,spline_cox,slope,730.0,,0.106016,-0.068774,0.542665,estimable_imprecise,estimable_imprecise

## Complexity-value table

For each non-reference candidate (`core_cox`, `elastic_net_cox`, `spline_cox`) compared with
`minimal_cox` on the same eligible patients and paired resamples: seven gains
(`auc_gain` x2, `ibs_gain`, `citl_gain` x2, `slope_gain` x2) and the locked mechanical classification
-- **clear added value**, **trade-off/uncertain**, or **no demonstrated advantage** -- produced
purely from the frozen rule, not a written conclusion. A competitive `minimal_cox` is a substantive
result, not a failed analysis.

In [9]:
classification_by_cell = result.complexity_value_summary.drop_duplicates(
    ["endpoint", "design", "centre", "fuller_model"]
)[["endpoint", "design", "centre", "fuller_model", "classification"]]
display(classification_by_cell)

display(
    result.complexity_value_summary[
        [
            "endpoint",
            "design",
            "centre",
            "fuller_model",
            "gain",
            "horizon",
            "value",
            "ci_lower",
            "ci_upper",
        ]
    ].head(21)
)

    endpoint  design centre     fuller_model             classification
0         OS    iecv   DFCI         core_cox        trade_off_uncertain
7         OS    iecv   DFCI  elastic_net_cox  no_demonstrated_advantage
14        OS    iecv   DFCI       spline_cox  no_demonstrated_advantage
21        OS  pooled   DFCI         core_cox        trade_off_uncertain
28        OS  pooled   DFCI  elastic_net_cox        trade_off_uncertain
35        OS  pooled   DFCI       spline_cox  no_demonstrated_advantage
42        OS    iecv    MSK         core_cox        trade_off_uncertain
49        OS    iecv    MSK  elastic_net_cox        trade_off_uncertain
56        OS    iecv    MSK       spline_cox  no_demonstrated_advantage
63        OS  pooled    MSK         core_cox        trade_off_uncertain
70        OS  pooled    MSK  elastic_net_cox        trade_off_uncertain
77        OS  pooled    MSK       spline_cox  no_demonstrated_advantage
84        OS    iecv   VICC         core_cox        trade_off_uncertain
91        OS    iecv   VICC  elastic_net_cox        trade_off_uncertain
98        OS    iecv   VICC       spline_cox  no_demonstrated_advantage
105       OS  pooled   VICC         core_cox        trade_off_uncertain
112       OS  pooled   VICC  elastic_net_cox        trade_off_uncertain
119       OS  pooled   VICC       spline_cox  no_demonstrated_advantage
126   TTNT-D    iecv   DFCI         core_cox        trade_off_uncertain
133   TTNT-D    iecv   DFCI  elastic_net_cox  no_demonstrated_advantage
140   TTNT-D    iecv   DFCI       spline_cox  no_demonstrated_advantage
147   TTNT-D  pooled   DFCI         core_cox        trade_off_uncertain
154   TTNT-D  pooled   DFCI  elastic_net_cox  no_demonstrated_advantage
161   TTNT-D  pooled   DFCI       spline_cox          clear_added_value
168   TTNT-D    iecv    MSK         core_cox          clear_added_value
175   TTNT-D    iecv    MSK  elastic_net_cox  no_demonstrated_advantage
182   TTNT-D    iecv    MSK       spline_cox          clear_added_value
189   TTNT-D  pooled    MSK         core_cox        trade_off_uncertain
196   TTNT-D  pooled    MSK  elastic_net_cox  no_demonstrated_advantage
203   TTNT-D  pooled    MSK       spline_cox  no_demonstrated_advantage
210   TTNT-D    iecv   VICC         core_cox        trade_off_uncertain
217   TTNT-D    iecv   VICC  elastic_net_cox  no_demonstrated_advantage
224   TTNT-D    iecv   VICC       spline_cox  no_demonstrated_advantage
231   TTNT-D  pooled   VICC         core_cox        trade_off_uncertain
238   TTNT-D  pooled   VICC  elastic_net_cox  no_demonstrated_advantage
245   TTNT-D  pooled   VICC       spline_cox  no_demonstrated_advantage

,endpoint,design,centre,fuller_model,gain,horizon,value,ci_lower,ci_upper
0,OS,iecv,DFCI,core_cox,auc,365.0,NaN,NaN,NaN
1,OS,iecv,DFCI,core_cox,auc,730.0,NaN,NaN,NaN
2,OS,iecv,DFCI,core_cox,ibs,,NaN,NaN,NaN
3,OS,iecv,DFCI,core_cox,citl,365.0,NaN,NaN,NaN
4,OS,iecv,DFCI,core_cox,citl,730.0,NaN,NaN,NaN
5,OS,iecv,DFCI,core_cox,slope,365.0,NaN,NaN,NaN
6,OS,iecv,DFCI,core_cox,slope,730.0,NaN,NaN,NaN
7,OS,iecv,DFCI,elastic_net_cox,auc,365.0,-0.015942,-0.125481,0.091990
8,OS,iecv,DFCI,elastic_net_cox,auc,730.0,0.010859,-0.043568,0.070108
9,OS,iecv,DFCI,elastic_net_cox,ibs,,0.002096,-0.004058,0.008447
10,OS,iecv,DFCI,elastic_net_cox,citl,365.0,0.092638,-0.093772,0.145577
11,OS,iecv,DFCI,elastic_net_cox,citl,730.0,0.105856,-0.047573,0.156189
12,OS,iecv,DFCI,elastic_net_cox,slope,365.0,0.024257,-0.907116,0.450295
13,OS,iecv,DFCI,elastic_net_cox,slope,730.0,0.020343,-0.263821,0.301422
14,OS,iecv,DFCI,spline_cox,auc,365.0,-0.038396,-0.159791,0.086128
15,OS,iecv,DFCI,spline_cox,auc,730.0,-0.001499,-0.060949,0.061588
16,OS,iecv,DFCI,spline_cox,ibs,,0.002523,-0.006040,0.011711
17,OS,iecv,DFCI,spline_cox,citl,365.0,0.110584,-0.109079,0.176992
18,OS,iecv,DFCI,spline_cox,citl,730.0,0.130645,-0.072549,0.190352
19,OS,iecv,DFCI,spline_cox,slope,365.0,-0.179435,-1.461975,0.519503
20,OS,iecv,DFCI,spline_cox,slope,730.0,-0.155368,-0.416610,0.302239

## Canonical artifacts and privacy scan

The workflow atomically publishes `evaluation_report.md`, `evaluation_manifest.json`,
`performance_summary.csv`, `transportability_summary.csv`, `complexity_value_summary.csv`,
`calibration_curves.csv`, and `entry_support_summary.csv`, plus panel figures under `figures/`,
under `analysis/out/current/evaluation/`. Every published artifact and this notebook's own output
contain no patient key, source identifier, exact patient time, per-patient prediction, linear
predictor, transformed row, or model coefficient -- only the aggregate counts and identifiers
displayed above.

In [10]:
display(
    pd.Series(
        {
            "evaluation_report": result.artifacts.evaluation_report.name,
            "evaluation_manifest": result.artifacts.evaluation_manifest.name,
            "performance_summary": result.artifacts.performance_summary.name,
            "transportability_summary": result.artifacts.transportability_summary.name,
            "complexity_value_summary": result.artifacts.complexity_value_summary.name,
            "calibration_curves": result.artifacts.calibration_curves.name,
            "entry_support_summary": result.artifacts.entry_support_summary.name,
            "figures": result.artifacts.figures.name,
            "directory": str(result.artifacts.directory),
        }
    )
)

evaluation_report                                        evaluation_report.md
evaluation_manifest                                  evaluation_manifest.json
performance_summary                                   performance_summary.csv
transportability_summary                         transportability_summary.csv
complexity_value_summary                         complexity_value_summary.csv
calibration_curves                                     calibration_curves.csv
entry_support_summary                               entry_support_summary.csv
figures                                                               figures
directory                   /Users/camilasarmiento/Documents/Data Freelanc...
dtype: object